### ISSUE TITLE
Warning: A non-numeric value encountered

### ISSUE THREAD

**Issue by mcdeimon** [VidYen/VYPS-Plugin#110]
Hi!

Today, without making any changes or doing anything new, this error has appeared on the miner's page.

Warning: A non-numeric value encountered in /var/www/vhosts/myweb.com/httpdocs/wp-content/plugins/vidyen-point-system-vyps/includes/shortcodes/vyps256.php on line 264

And the miner does not connect to the server.

The line 264 is this:

`$balance = intval($remote_response['body'] / $hash_per_point);`

Thanks!

**Comment by VidYen** [comment]
Oh that wasn't you or VYPS. The Web socket server crashed while I was sleeping.

I just rebooted.

Normally it should kick over to the other server, but it didn't kick over to backup as it was up but giving an error 502 Bad Gateway rather than no response.

I will keep an eye on the server, but I am going to leave this as an issue for VYPS to not only check it gets a response but if it gets a non number value from server, it knows it should just check the backup.

**Comment by VidYen** [comment]
@mcdeimon

Please try again and let me know if it works for you or not. Notgiven688 has some stability updates for the websocket server (memory stuff), but was waiting for the v2 cryptonight to pass that through to our changes.

**Comment by VidYen** [comment]
On line 254ish I need to just check `$remote_response =  wp_remote_get( esc_url_raw( $remote_url ) );`

See if its an actual number rather than an error and if its error then tell it to try next server.

**Comment by mcdeimon** [comment]
Now it works perfectly! Thank you!!!

**Comment by mcdeimon** [comment]
It appears again...

**Comment by VidYen** [comment]
Fixed. Going to have it fixed permantly soon.

**Comment by VidYen** [comment]
I believe. Other than me messing the the servers... This should be fixed permanently for now.

**Comment by VidYen** [comment]
Ok. This has been fixed permantly to the best of my knowledge. Unless I kill the server.exe for some unknown reason.
